spring:
  datasource:
    username: root
    password: root
    url: jdbc:mysql:///scheduling?serverTimezone=Asia/Shanghai

  jpa:
    database: mysql
    database-platform: mysql
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL57Dialect